### ISSUE TITLE
Separate plotting

### ISSUE THREAD

**Issue by dehann** [dehann/KernelDensityEstimate.jl#3]
Functionality should continue to work, since plotting requires much more user infrastructure.

Maybe a separate package like:

KernelDensityPlotting.jl

Will be useful for all three the KDE\* .jl packages out there. Have 1D, and several 2D for multidimensional, as well as contour density evaluation.

cc @wadehenning (as FYI)

**Comment by GordStephen** [comment]
Big 👍 for this, particularly since binary dependencies are involved which significantly increases the likelihood of build issues across various platforms and complicates non-root installations. Much like the issue in #1 I also had to remove strip out the plotting functionality to get this successfully installed as a non-privileged user on RHEL.

**Comment by dehann** [comment]
Yeah, sorry guys I still have to do this -- it's fallen a bit behind...

**Comment by wadehenning** [comment]
The package has been working well for me since Julia 0.5.

**Comment by dehann** [comment]
Please see work in progress at #18
